#Question No.1
pnorm(2.64,0,1,lower.tail = FALSE)
pnorm(1.39,0,1,lower.tail = FALSE)+ pnorm(-1.39,0,1)
UCBAdmissions
univ <- apply(UCBAdmissions,c(1,3),sum)
univ
univ <- as.data.frame(univ)
data <- t(univ)
data <-  as.data.frame(data)
head(data)
library(dplyr)
data <- mutate(data, "Applied" = Admitted + Rejected)
data <- mutate(data, "AccRate" = Admitted / Applied)
data
prop.test(mean(data$Admitted), mean(data$Applied),0.4,"less", 0.98, TRUE)
dfUCB <- as.data.frame(UCBAdmissions)
head(dfUCB)
library(sqldf)
sqldf('select * from dfUCB where Admit like "Admitted"')
mfdata <- sqldf('select * from dfUCB where Admit like "Admitted"')
mfdata <- cbind(mfdata,sqldf('select Admit,Freq from dfUCB where Admit like "Rejected"'))
mfdata
colnames(mfdata)[c(1,5)] <- c("Offered","Denied")
colnames(mfdata)[c(4,6)] <- c("FreqOff","FreqDeni")
mfdata <- mutate(mfdata, "Applied" = FreqOff + FreqDeni)
mfdata <- mutate(mfdata, "AccRate" = FreqOff / Applied)
prop.test(mean(mfdata$FreqOff), mean(mfdata$Applied), 0.4,"less", 0.98, TRUE)
pnorm(0.4,mean(mfdata$AccRate),sd(mfdata$AccRate))
mean(mfdata$AccRate)
sd(mfdata$AccRate)
save.image("E:/kamagyana/Computing/DARET/Submissions/Asst9.1.r.RData")
load("E:/kamagyana/Computing/DARET/Submissions/Asst9.1.r.RData")
mfdata
sum(mfdata$Applied)
sum(mfdata$FreqOff)
sum(mfdata$FreqOff) / sum(mfdata$Applied)
sqrt((0.4 * (1 - 0.4))/(sum(mfdata$Applied)))
pnorm(0.4,mean(mfdata$AccRate,sqrt((0.4 * (1 - 0.4))/(sum(mfdata$Applied)))))
pnorm(mean(mfdata$AccRate,0.4,sqrt((0.4 * (1 - 0.4))/(sum(mfdata$Applied)))))
savehistory("E:/kamagyana/Computing/DARET/Submissions/Asst9.1.r")
